kind: ReplicationController
apiVersion: v1
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: kube-dns
  template:
    metadata:
      labels:
        k8s-app: kube-dns
        kubernetes.io/cluster-service: "true"
    spec:
      restartPolicy: Always
      dnsPolicy: Default
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:v2.3.1
        imagePullPolicy: IfNotPresent
        args:
        - "--listen-peer-urls=http://127.0.0.1:2380"
        - "--listen-client-urls=http://127.0.0.1:2379"
        - "--advertise-client-urls=http://127.0.0.1:2379"
        - "--data-dir=/var/etcd/data"
      - name: kube2sky
        image: gcr.io/google_containers/kube2sky:1.14
        imagePullPolicy: IfNotPresent
        args:
        #- "--kube-master-url=http://127.0.0.1:8080"
        - "--etcd-server=http://127.0.0.1:2379"
        - "--domain=cluster.local"
      - name: skydns
        image: skynetservices/skydns:2.5.3a
        imagePullPolicy: IfNotPresent
        args:
        - "--machines=http://127.0.0.1:2379"
        - "--addr=0.0.0.0:53"
        - "--domain=cluster.local."
        - "--ns-rotate=false"
        #- "--nameservers=8.8.8.8:53,8.8.4.4:53"
        ports:
        - name: dns
          containerPort: 53
          protocol: UDP
        - name: dns-tcp
          containerPort: 53
          protocol: TCP
      - name: healthz
        image: gcr.io/google_containers/exechealthz:1.0
        imagePullPolicy: IfNotPresent
        args:
          - "-cmd=nslookup kubernetes.default.svc.cluster.local 127.0.0.1 >/dev/null"
          - "-port=8080"
        ports:
        - containerPort: 8080
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: kube-dns
  namespace: kube-system
  labels:
    k8s-app: kube-dns
    kubernetes.io/name: KubeDNS
    kubernetes.io/cluster-service: "true"
spec:
  selector:
    k8s-app: kube-dns
  clusterIP: 10.0.0.10
  ports:
  - protocol: UDP
    name: dns
    port: 53
  - protocol: TCP
    name: dns-tcp
    port: 53
